### PR TITLE
2.0 - Add `IDefinitionStore` specification & reference implementation + Various improvements

### LINKED ISSUE #23: Test parallelization failure: File loading issue
### On the feature/defs-filestore branch (tied to issue #22), tests will not run in parallel.  

This is due to an issue with file loading, where deflating the stream causes an exception in a concurrent file access situation.
See an excerpt from [this GHA failed run](https://github.com/Nodsoft/WoWS-ReplaysUnpack/runs/8292598862?check_suite_focus=true):

```
[xUnit.net 00:00:01.63]     Nodsoft.WowsReplaysUnpack.Tests.ReplaySanitizerTests.TestGoodReplay_Pass [FAIL]
[xUnit.net 00:00:01.70]     Nodsoft.WowsReplaysUnpack.Tests.ReplayParsingExecutionTests.TestFilesystemParsing [FAIL]
[xUnit.net 00:00:02.35]     Nodsoft.WowsReplaysUnpack.Tests.ReplaySanitizerTests.TestPayloadReplayDetection [FAIL]
[xUnit.net 00:00:02.41]     Nodsoft.WowsReplaysUnpack.Tests.ReplayParsingExecutionTests.TestDefaultParsing [FAIL]
  Failed Nodsoft.WowsReplaysUnpack.Tests.ReplaySanitizerTests.TestGoodReplay_Pass [667 ms]
  Error Message:
   System.IO.InvalidDataException : The archive entry was compressed using an unsupported compression method.
  Stack Trace:
     at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Decompress(Stream compressedStream, Stream decompressedStream) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 172
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Unpack(Stream stream, ReplayUnpackerOptions options) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 96
   at Nodsoft.WowsReplaysUnpack.Tests.ReplaySanitizerTests.TestGoodReplay_Pass() in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack.Tests/ReplaySanitizerTests.cs:line 33
  Failed Nodsoft.WowsReplaysUnpack.Tests.ReplayParsingExecutionTests.TestFilesystemParsing [756 ms]
  Error Message:
   System.IO.InvalidDataException : The archive entry was compressed using an unsupported compression method.
  Stack Trace:
     at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Decompress(Stream compressedStream, Stream decompressedStream) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 172
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Unpack(Stream stream, ReplayUnpackerOptions options) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 96
   at Nodsoft.WowsReplaysUnpack.Tests.ReplayParsingExecutionTests.TestFilesystemParsing() in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack.Tests/ReplayParsingExecutionTests.cs:line 61
  Failed Nodsoft.WowsReplaysUnpack.Tests.ReplaySanitizerTests.TestPayloadReplayDetection [711 ms]
  Error Message:
   Assert.Throws() Failure
Expected: typeof(Nodsoft.WowsReplaysUnpack.Core.Exceptions.CveSecurityException)
Actual:   typeof(System.IO.InvalidDataException): The archive entry was compressed using an unsupported compression method.
---- System.IO.InvalidDataException : The archive entry was compressed using an unsupported compression method.
  Stack Trace:
     at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Decompress(Stream compressedStream, Stream decompressedStream) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 172
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Unpack(Stream stream, ReplayUnpackerOptions options) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 96
   at Nodsoft.WowsReplaysUnpack.Tests.ReplaySanitizerTests.<TestPayloadReplayDetection>b__3_0() in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack.Tests/ReplaySanitizerTests.cs:line 43
----- Inner Stack Trace -----
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Decompress(Stream compressedStream, Stream decompressedStream) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 172
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Unpack(Stream stream, ReplayUnpackerOptions options) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 96
   at Nodsoft.WowsReplaysUnpack.Tests.ReplaySanitizerTests.<TestPayloadReplayDetection>b__3_0() in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack.Tests/ReplaySanitizerTests.cs:line 43
  Failed Nodsoft.WowsReplaysUnpack.Tests.ReplayParsingExecutionTests.TestDefaultParsing [711 ms]
  Error Message:
   System.IO.InvalidDataException : The archive entry was compressed using an unsupported compression method.
  Stack Trace:
     at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Decompress(Stream compressedStream, Stream decompressedStream) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 172
   at Nodsoft.WowsReplaysUnpack.Services.ReplayUnpackerService`1.Unpack(Stream stream, ReplayUnpackerOptions options) in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:line 96
   at Nodsoft.WowsReplaysUnpack.Tests.ReplayParsingExecutionTests.TestDefaultParsing() in /home/runner/work/WoWS-ReplaysUnpack/WoWS-ReplaysUnpack/Nodsoft.WowsReplaysUnpack.Tests/ReplayParsingExecutionTests.cs:line [30](https://github.com/Nodsoft/WoWS-ReplaysUnpack/runs/8292598862?check_suite_focus=true#step:7:31)
```

### PR DESCRIPTION
**Pull request by SakuraIsayeki**

### CODE REVIEW

File: Nodsoft.WowsReplaysUnpack.FileStore/Definitions/FileSystemDefinitionLoader.cs [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+		// so we'll need to parse them accordingly into Version objects.
+		Version[] versions = new DirectoryInfo(_options.CurrentValue.RootDirectory).GetDirectories()
+			.Select(static dir => FromFilesystemString(dir.Name))
+			.OrderByDescending(static version => version)
+			.ToArray();
+		
+		return versions;
+	}
+	
+	[MethodImpl(MethodImplOptions.AggressiveInlining)]
```
Comment (stewieoO) [inline Nodsoft.WowsReplaysUnpack.FileStore/Definitions/FileSystemDefinitionLoader.cs]: Why though :D
The GetSupportedVersion() method is called only once when the store is constructed.
To my knowledge the aggressive inlining is only usefull in some edgecases on hotpaths with a fuckton of calls to it

File: Nodsoft.WowsReplaysUnpack.FileStore/Definitions/FileSystemDefinitionLoaderOptions.cs [hunk 2]
```diff
@@ -0,0 +1,17 @@
+﻿namespace Nodsoft.WowsReplaysUnpack.FileStore.Definitions;
+
+/// <summary>
+/// Defines settings for the <see cref="FileSystemDefinitionLoader"/>.
+/// </summary>
+public record FileSystemDefinitionLoaderOptions
```
Comment (stewieoO) [inline Nodsoft.WowsReplaysUnpack.FileStore/Definitions/FileSystemDefinitionLoaderOptions.cs]: I know you love records, but don't you remember when we had a chat about it?
If you don't need it's special features (like equality and immutability) it actually adds more overhead than a normal class.
Not that it really matters for an options object that's only there once. But you know, gotta mention it :D

File: Nodsoft.WowsReplaysUnpack.Tests/Utilities.cs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+namespace Nodsoft.WowsReplaysUnpack.Tests;
+
+/// <summary>
+/// Helper methods used in tests.
+/// </summary>
+public static class Utilities
+{
+	private static readonly string _sampleFolder = Path.Join(Directory.GetCurrentDirectory(), "Replay-Samples");
+	
+	[MethodImpl(MethodImplOptions.AggressiveInlining)]
```
Comment (stewieoO) [inline Nodsoft.WowsReplaysUnpack.Tests/Utilities.cs:12]: 🤐

File: Nodsoft.WowsReplaysUnpack/ReplayUnpackerBuilder.cs [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+	/// <returns>The builder.</returns>
+	public ReplayUnpackerBuilder WithDefinitionStore<TStore>() where TStore : class, IDefinitionStore
+	{
+		Services.AddSingleton<IDefinitionStore, TStore>();
+		definitionStoreAdded = true;
+		return this;
+	}
+
+
+  // stewie says: No need for that since they will be added either way if you don't add other ones
```
Comment (stewieoO) [inline Nodsoft.WowsReplaysUnpack/ReplayUnpackerBuilder.cs:79]: i said what? 😆

File: Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs [hunk 5]
```diff
@@ -100,14 +106,13 @@ public UnpackedReplay Unpack(Stream stream, ReplayUnpackerOptions? options = nul
 		// Decrypted stream not used anymore
 		decryptedStream.Dispose();
 
-
 		Version gameclientVersion = Version.Parse(arenaInfo.ClientVersionFromExe.Replace(',', '.'));
-		
+		_semaphore.Wait(_semephoreTimeOut);
```
Comment (stewieoO) [inline Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:110]: I saw this was added to "prevent a deadlock" but i'm curious what resource was actually deadlocked?
And this should definitely be a configurable option.

**Review by stewieoO — CHANGES_REQUESTED** [review]

File: Nodsoft.WowsReplaysUnpack.FileStore/Definitions/FileSystemDefinitionLoader.cs (hunk 1 above)
Comment (HenryQuan) [reply Nodsoft.WowsReplaysUnpack.FileStore/Definitions/FileSystemDefinitionLoader.cs]: If it is only used once, maybe this function itself can be removed. Inline is useful for tiny functions at least for C++, not sure what C# does. Also, the compiler may make some functions Inline with optimisation turned on.

File: Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs (hunk 5 above)
Comment (HenryQuan) [reply Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:110]: I believe the deadlock still exists in this pull request when there are many threads like 12 or even more. It is also likely to happen in test. The reason behind is still unknown, I believe some functions are still holding the semephore in rare occasions.
The true root cause was that the implementation didn't consider thread safety in the first place. A rewrite may be required for this to work properly. However, it can be time consuming.

Comment (stewieoO) [reply Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:110]: @HenryQuan do you know what gets deadlocked though? Does it only happen when files are read from the filesystem or also when it's coming from memory? Or is it purely because it's not async? I'm fairly certain i had it async at the start but then changed it back because it made no sense somewhere...

File: Nodsoft.WowsReplaysUnpack.FileStore/Definitions/FileSystemDefinitionLoader.cs (hunk 1 above)
Comment (stewieoO) [reply Nodsoft.WowsReplaysUnpack.FileStore/Definitions/FileSystemDefinitionLoader.cs]: This too yeah, the compiler already inlines by itself where it can. The attribute is just a "heavy suggestion" to the compiler to do this. It's not even guaranteed. But as i said, unless it's on a hotpath with LOTS of calls, it won't have any advantage.

File: Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs (hunk 5 above)
Comment (HenryQuan) [reply Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:110]: The issue without semephores was due to the decryption. Please see, https://github.com/Nodsoft/WoWS-ReplaysUnpack/pull/29#issue-1921067190. I don't understand why `BinaryReader` isn't thread safe. It seems that other threads are changing its pointer also as it is like a singleton. With semephores, in a heavy multithread condition, there may be some deadlocks. Not sure what is blocking it because there shouldn't be any locks. We probably to investigate further on this. I am not very familar with C# semephore also.

Comment (stewieoO) [reply Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:110]: Ah, so initially the issue wasn't deadlocks but some weird errors with the BinaryReader and now with the added Semaphore there's the potential for deadlocks?

Also the issue you mentioned is about the new file system file store right?

So am i right in assuming the previous issue and the deadlocks only happen with the file system store and not when it's coming from memory?

Comment (HenryQuan) [reply Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:110]: That's correct I believe. Maybe, it is a lock coming from the file system. I have not tested with the memory approach yet.

Comment (stewieoO) [reply Nodsoft.WowsReplaysUnpack/Services/ReplayUnpackerService.cs:110]: That would make more sense yeah. I wouldn't even know where to begin if it's not caused by the file system...
I just had a quick look at the code cause i couldn't quite remember but i think the issue could be that the definitions are loaded on-demand and then cached for future access.
This wasn't an issue when i first implemented it with the embedded resources i guess, but when you open them from the FS there's a potential for file locks or whatever. So maybe the filesystem loader just needs a lock(obj) thingy inside the GetFileAsXml method. it will be slower for the first access of each definition (if there's multiple threads doing it at the same time) but then they're cached anyways.

**Comment by stewieoO** [comment]
@SakuraIsayeki forgot one thing, the readme needs to be updated.
The description for the `IDefinitionStore` is not correct anymore and a description for `IDefinitionLoader` needs to be added

**Review by stewieoO — APPROVED** [review]

**Comment by SakuraIsayeki** [comment]
Merging this PR now, pending follow-up on outstanding issues :
- README needs to be updated to include `IDefinitionLoader` and subsequently update `IDefinitionStore`.
- Deadlock issue should be investigated separately, yet is not a blocking issue (high risk, low impact).
